packages:
  - "apps/*"
  - "packages/*"

nodeLinker: hoisted

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild

ignoredBuiltDependencies:
  - dtrace-provider
  - msgpackr-extract

allowBuilds:
  better-sqlite3: true
  dtrace-provider: false
  esbuild: true
  msgpackr-extract: false

minimumReleaseAgeExclude:
  - xstate@6.0.0-alpha.18
