/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as PlansNewRouteImport } from './routes/plans.new'
import { Route as FoodsNewRouteImport } from './routes/foods.new'
import { Route as FoodsEditRouteImport } from './routes/foods.edit'
import { Route as DaysDateKeyRouteImport } from './routes/days.$dateKey'
import { Route as PlansPlanIdEditRouteImport } from './routes/plans.$planId.edit'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const PlansNewRoute = PlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsNewRoute = FoodsNewRouteImport.update({
  id: '/foods/new',
  path: '/foods/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsEditRoute = FoodsEditRouteImport.update({
  id: '/foods/edit',
  path: '/foods/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DaysDateKeyRoute = DaysDateKeyRouteImport.update({
  id: '/days/$dateKey',
  path: '/days/$dateKey',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdEditRoute = PlansPlanIdEditRouteImport.update({
  id: '/plans/$planId/edit',
  path: '/plans/$planId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRouteWithChildren
  '/days/$dateKey': typeof DaysDateKeyRoute
  '/foods/edit': typeof FoodsEditRoute
  '/foods/new': typeof FoodsNewRoute
  '/plans/new': typeof PlansNewRoute
  '/insights/': typeof InsightsIndexRoute
  '/plans/$planId/edit': typeof PlansPlanIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/days/$dateKey': typeof DaysDateKeyRoute
  '/foods/edit': typeof FoodsEditRoute
  '/foods/new': typeof FoodsNewRoute
  '/plans/new': typeof PlansNewRoute
  '/insights': typeof InsightsIndexRoute
  '/plans/$planId/edit': typeof PlansPlanIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRouteWithChildren
  '/days/$dateKey': typeof DaysDateKeyRoute
  '/foods/edit': typeof FoodsEditRoute
  '/foods/new': typeof FoodsNewRoute
  '/plans/new': typeof PlansNewRoute
  '/insights/': typeof InsightsIndexRoute
  '/plans/$planId/edit': typeof PlansPlanIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/days/$dateKey'
    | '/foods/edit'
    | '/foods/new'
    | '/plans/new'
    | '/insights/'
    | '/plans/$planId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/days/$dateKey'
    | '/foods/edit'
    | '/foods/new'
    | '/plans/new'
    | '/insights'
    | '/plans/$planId/edit'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/days/$dateKey'
    | '/foods/edit'
    | '/foods/new'
    | '/plans/new'
    | '/insights/'
    | '/plans/$planId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  DaysDateKeyRoute: typeof DaysDateKeyRoute
  FoodsEditRoute: typeof FoodsEditRoute
  FoodsNewRoute: typeof FoodsNewRoute
  PlansNewRoute: typeof PlansNewRoute
  PlansPlanIdEditRoute: typeof PlansPlanIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/plans/new': {
      id: '/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof PlansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/new': {
      id: '/foods/new'
      path: '/foods/new'
      fullPath: '/foods/new'
      preLoaderRoute: typeof FoodsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/edit': {
      id: '/foods/edit'
      path: '/foods/edit'
      fullPath: '/foods/edit'
      preLoaderRoute: typeof FoodsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/days/$dateKey': {
      id: '/days/$dateKey'
      path: '/days/$dateKey'
      fullPath: '/days/$dateKey'
      preLoaderRoute: typeof DaysDateKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId/edit': {
      id: '/plans/$planId/edit'
      path: '/plans/$planId/edit'
      fullPath: '/plans/$planId/edit'
      preLoaderRoute: typeof PlansPlanIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InsightsRouteChildren {
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRouteWithChildren,
  DaysDateKeyRoute: DaysDateKeyRoute,
  FoodsEditRoute: FoodsEditRoute,
  FoodsNewRoute: FoodsNewRoute,
  PlansNewRoute: PlansNewRoute,
  PlansPlanIdEditRoute: PlansPlanIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
